name: Build Custom Rates

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Windows
            os: windows-latest
          - name: Android32
            os: ubuntu-latest
            target: Android32
          - name: Android64
            os: ubuntu-latest
            target: Android64

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - checkout:
        uses: actions/checkout@v4

      - name: Build Mod
        uses: geode-sdk/build-geode-mod@main
        with:
          # Вот эта часть заставит CMake увидеть SDK
          build-config: |
            -DGeode_DIR=$GEODE_SDK
            -DCMAKE_PREFIX_PATH=$GEODE_SDK
          sdk: v5.5.3
          target: ${{ matrix.config.target }}
          combine: true
