name: Build Android Mod
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Установка инструментов Geode
      - name: Setup Geode
        uses: geode-sdk/setup-geode@main

      # Самая простая команда сборки
      - name: Build
        uses: geode-sdk/build-geode-mod@main
        with:
          sdk: v3.7.0
          target: Android64 # Начни с одной версии (64 бит), так быстрее
          combine: true
